
norun:
	echo "Rename from run*.sh to Run*.sh"
	mv run_negExpiredKbTicket.sh Run_negExpiredKbTicket.sh
	mv run_negLongExpiredKbTkt.sh Run_negLongExpiredKbTkt.sh
	mv run_negNoKbTicket.sh Run_negNoKbTicket.sh

torun:
	echo "Rename from Run*.sh to Run*.sh"
	mv Run_negExpiredKbTicket.sh run_negExpiredKbTicket.sh
	mv Run_negLongExpiredKbTkt.sh run_negLongExpiredKbTkt.sh
	mv Run_negNoKbTicket.sh run_negNoKbTicket.sh

