version: 4
shared:
  settings:
    email: 

jobs:
  component:
    template: v3-platform/python-component@stable
    steps:
      - doc_build: make -f ./Makefile build
      - package_publish: echo 'skip'
      - tag_release: echo 'skip'      
      - test: echo 'skip'            
      - doc_publish: make -f ./Makefile publish
    requires:
      - ~commit
      - ~pr
