platform: cpp

shared:
    notifications:
      email: rchopde@yahoo-inc.com

    build_containers: [rhel6]
    publish_containers: [rhel6]
    steps:
        update_metadata:
            description: Update_metadata
            command: ./cicd/update_metadata.sh master
        yinst_create:
            description: Build the package 
            command: yinst_create -r hadoopqa_headless_keys 
        dist_install:
            description: Push the package to Dist 
            command: dist_install hadoopqa_headless_keys.tgz 
    plugins:
      coverage:
        enabled: false
      test_results:
        enabled: false
jobs:
   component:
      order: [init, install-jdk, clean, build, update_metadata]
   pull-request:
      order: [init, install-jdk, clean, build]
   build_hadoopqa_headless_keys: 
      order: [yinst_create, dist_install]

