platform: cpp

shared:
	notifications:
	  email: rchopde@yahoo-inc.com

	build_containers: [rhel6]
	publish_containers: [rhel6]
	
	plugins:
	  coverage:
	    enabled: false
	  test_results:
	    enabled: false

	triggers:
	- url: "http://re101.ygrid.corp.gq1.yahoo.com:9999/yhudson/job/Hadoop-Cluster-Deploy-Grid-VM"
	params:
		CLUSTER: openqe30blue

jobs:
   component:
	order: [init, install-jdk, clean, build, test]
