shared:
    template: HadoopTools/gridci@latest
    settings:
      email: rchopde@verizonmedia.com
    environment:
      SKIP_VALIDATION: "true"
      DIST_TAG: HADOOP_2_8_0_LATEST

parameters:
    TEST_TAG: "HADOOP_2_8_0_LATEST"
    CERTIFIED_TAG: "deploy_hadoop_latest_certified_release"
    CLUSTERS: "all"
    CLUSTERS_TO_PROMOTE: "axonitered"
    UPLOAD_ARTIFACTORY: "true"
    UPDATE_RELEASE: "true"
    TGZ_VERSION: "2.10.1"

jobs:
    pull_request:
        requires: [~pr]
        steps:
          - info: echo "PR build"
          - build: gmake pr_build
          - junit: echo "DISABLED"
          - regression: echo "DISABLED"
          - package: echo "DISABLED"
          - postpackage: echo "DISABLED"
          - publish: echo "DISABLED"
          - git_tag: echo "DISABLED"
          - dist_tag: echo "DISABLED"
          - bundle: echo "DISABLED"
    promote-cd-tag:
        requires: [~commit]
        steps:
          - info: echo "Promote release dist tag to certified tag"
          - preprebuild: 'echo "TEST_TAG: $(meta get parameters.TEST_TAG.value),\
                                CERTIFIED_TAG: $(meta get parameters.CERTIFIED_TAG.value),\
                                UPLOAD_ARTIFACTORY: $(meta get parameters.UPLOAD_ARTIFACTORY.value)"'
          - prebuild: 'echo "CLUSTERS: $(meta get parameters.CLUSTERS.value), \
                             CLUSTERS_TO_PROMOTE: $(meta get parameters.CLUSTERS_TO_PROMOTE.value), \
                             UPDATE_RELEASE: $(meta get parameters.UPDATE_RELEASE.value)"'
          - build: sudo yum install perl-Test-Simple perl-Tie-IxHash -y;yinst i perl_ykeykey; yinst i dist_tools -br test;./deploySupport/promote_pkgs -test_tag $(meta get parameters.TEST_TAG.value) -cert_tag $(meta get parameters.CERTIFIED_TAG.value) -clusters $(meta get parameters.CLUSTERS.value)
          - junit: echo "Disabled"
          - regression: echo "DISABLED"
          - package: echo "Disabled"
          - publish: echo "Disabled"
          - git_tag: echo "Disabled"
          - dist_tag: echo "Disabled"
    gen_hadoop_release:
        annotations:
          screwdriver.cd/cpu: HIGH
          screwdriver.cd/ram: HIGH
          screwdriver.cd/timeout: 720
        template: HadoopTools/gridci@latest
        environment:
          UPDATE_RELEASE: true
          DIST_TAG: HADOOP_2_8_0_TEST
        requires: [promote-cd-tag]
        steps:
          - info: echo "Generate deploy packages and upload bundles"
          - build: gmake build; sh -x deploySupport/makerelease.sd
          - junit: echo "DISABLED"
          - regression: echo "DISABLED"
          - package: echo "DISABLED"
          - postpackage: echo "DISABLED"
          - publish: echo "DISABLED"
          - git_tag: echo "DISABLED"
          - dist_tag: echo "DISABLED"
    upload_bd_bundle:	
        annotations:	
          screwdriver.cd/cpu: HIGH	
          screwdriver.cd/ram: HIGH	
          screwdriver.cd/timeout: 720	
        template: HadoopTools/gridci@latest	
        environment:	
          UPDATE_RELEASE: true	
          DIST_TAG: HADOOP_2_8_0_TEST	
        requires: [gen_hadoop_release]	
        steps:	
          - build: sh -x deploySupport/generate_bundle	
          - junit: echo "DISABLED"	
          - regression: echo "DISABLED"	
          - package: echo "DISABLED"	
          - postpackage: echo "DISABLED"	
          - publish: echo "DISABLED"	
          - git_tag: echo "DISABLED"	
          - dist_tag: echo "DISABLED"
    conf_to_artifactory:
        annotations:
          screwdriver.cd/cpu: HIGH
          screwdriver.cd/ram: HIGH
          screwdriver.cd/timeout: 720
        template: HadoopTools/gridci@latest
        environment:
          UPDATE_RELEASE: false
          DIST_TAG: HADOOP_2_8_0_LATEST
        steps:
          - restore_yidfs: echo "Disabled"
          - build: gmake build; sh -x deploySupport/makerelease.sd
          - junit: echo "DISABLED"
          - regression: echo "DISABLED"
          - package: echo "DISABLED"
          - postpackage: echo "DISABLED"
          - publish: echo "DISABLED"
          - git_tag: echo "DISABLED"
          - dist_tag: echo "DISABLED"
