platform: cpp

shared:
    notifications:
      email: rchopde@yahoo-inc.com

    build_containers: [rhel6]
    publish_containers: [rhel6]
    steps:
        update_metadata:
            description: Update_metadata
            command: ./cicd/update_metadata.sh master

    plugins:
      coverage:
        enabled: false
      test_results:
        enabled: false

jobs:
   component:
      order: [init, install-jdk, clean, build, update_metadata]
   pull-request:
      order: [init, install-jdk, clean]
