platform: cpp

shared:
    notifications:
      email: grid-re@oath.com

    build_containers: [rhel6]
    publish_containers: [rhel6]
    steps:
        run_makerelease:
            description: Run makerelease 
            command: sh -x deploySupport/makerelease.sd

    plugins:
      coverage:
        enabled: false
      test_results:
        enabled: false

jobs:
   component:
      order: [init, install-jdk, clean, build, run_makerelease]
   pull-request:
      order: [init, install-jdk, clean]
