#!/bin/bash

if [ $# -ne 1 ];then
  echo "Error: need the CLUSTER name to compile against"
  exit 1
fi
CLUSTER=$1
echo "Info: building against $CLUSTER"


if [ ! -d outTokenRenewalTest_existingUgi_oldApi ]
then
  mkdir outTokenRenewalTest_existingUgi_oldApi
fi 

javac -Xlint:deprecation -Xlint:unchecked  -cp  `/home/gs/gridre/yroot.$CLUSTER/share/hadoop/bin/hadoop  --config /home/gs/gridre/yroot.$CLUSTER/conf/hadoop  classpath` -d outTokenRenewalTest_existingUgi_oldApi TokenRenewalTest_existingUgi_oldApi.java
if [ $? -ne 0 ]
then
   echo "Error compiling"
   exit 1
fi

jar -cvf TokenRenewalTest_existingUgi_oldApi.jar -C outTokenRenewalTest_existingUgi_oldApi .
if [ $? -ne 0 ]
then
   echo "Error packaging jar"
   exit 1
fi

echo "RUNME: /home/gs/gridre/yroot.$CLUSTER/share/hadoop/bin/hadoop --config /home/gs/gridre/yroot.$CLUSTER/conf/hadoop/ jar `pwd`/TokenRenewalTest_existingUgi_oldApi.jar TokenRenewalTest_existingUgi_oldApi" 

