#!/bin/bash
set -x #echo on

# This script should be used to gather dependencies from a developer machine
# so that they can be checked into the framework repository.  The script
# takes all current jars from the local user's .m2 repository and puts them
# in a directory "dependencies" at the top level of the framework.  The script
# will wipe out the existing local m2 repository and run maven eclipse:eclipse
# targets, so use with care.
#
# When adding new maven plugins to the maven configuration for the project,
# you will need to add the plugin dependencies here.  The maven plugin 
# dependencies need to be installed to the local repository so they are 
# available in maven offline mode on the grid.

# Set the base directory as the dir that the script lives in.
BASEDIR="$( cd "$( dirname "$0" )" && pwd )"

# Remove all preexisting maven local dependencies
rm -rf ~/.m2/*

# Clean the existing dependencies directory
rm -rf $BASEDIR/../dependencies

# install maven plugin dependencies to local repo.
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.codehaus.mojo:exec-maven-plugin:1.2.1:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-jar-plugin:2.2:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-javadoc-plugin:2.9:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-antrun-plugin:1.7:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-jar-plugin:2.4:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-surefire-plugin:2.13:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-compiler-plugin:2.3.2:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-resources-plugin:2.5:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-clean-plugin:2.4.1:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-install-plugin:2.3.1:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-site-plugin:3.0:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-plugins:21:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-parent:20:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-dependency-plugin:2.1:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-release-plugin:2.0:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.surefire:surefire-junit47:2.13:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.surefire:surefire-providers:2.13:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.surefire:common-junit48:2.13:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.surefire:common-junit4:2.13:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.surefire:common-junit3:2.13:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.surefire:common-java5:2.13:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.shared:maven-shared-components:18:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=com.google.code.findbugs:jsr305:2.0.1:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.surefire:surefire-grouper:2.13:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.plugins:maven-help-plugin:2.2
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.jacoco:jacoco-maven-plugin:0.6.2.201302030002
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.jacoco:org.jacoco.agent:0.6.2.201302030002
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.jacoco:org.jacoco.ant:0.6.2.201302030002
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=junit:junit:4.8.2
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=ant-contrib:ant-contrib:20020829
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.shared:maven-common-artifact-filters:1.1:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.codehaus.plexus:plexus-interpolation:1.7:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.codehaus.plexus:plexus-archiver:1.0-alpha-12:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.shared:maven-filtering:1.0-beta-2:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.codehaus.plexus:plexus-active-collections:1.0-beta-2:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.codehaus.plexus:plexus-io:1.0-alpha-4:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven:maven-archiver:2.4:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.codehaus.plexus:plexus-utils:2.0.1:jar
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.apache.maven.shared:maven-repository-builder:1.0-alpha-2:jar

# Get the dependencies for the project and build it
cd $BASEDIR/..
mvn eclipse:eclipse
mvn clean package -DskipTests

# Copy the local .m2 repo into the dependencies dir.
mkdir $BASEDIR/../dependencies
cp -R ~/.m2 $BASEDIR/../dependencies/

# Print out the size on disk for the .m2 and dependencies dirs.  They should
# match.
du -sk ~/.m2
du -sk $BASEDIR/../dependencies

# Add the dependencies to the git commit.  --all option adds new files,
# removes files in the repo no longer there on disk, and stages modified
# files that already exist in the repo.
git add --force --all $BASEDIR/../dependencies/*

