#!/bin/sh

echo "========== Test Related Exported variables ================="
## Passed value 
export WORKSPACE=$1; echo "WORKSPACE=$WORKSPACE"
export JOBS_SCRIPTS_DIR=$2; echo "JOBS_SCRIPTS_DIR=$JOBS_SCRIPTS_DIR"
export JOB_SCRIPTS_DIR_NAME=$3; echo "JOB_SCRIPTS_DIR_NAME=$JOB_SCRIPTS_DIR_NAME"
export ARTIFACTS_DIR=$4; echo "ARTIFACTS_DIR=$ARTIFACTS_DIR"
export LOCAL_RESULT=$5; echo "LOCAL_RESULT=$LOCAL_RESULT"
export JOB=$6; echo "JOB=$JOB"
export STARTTIME=$7; echo "STARTTIME=$STARTTIME"
export TMPDIR=$8; echo "TMPDIR=$TMPDIR"
export ARTIFACTS_FILE=$9; echo "ARTIFACTS_FILE=$ARTIFACTS_FILE"
export TEST_SUMMARY_ARTIFACTS=${10}; echo "TEST_SUMMARY_ARTIFACTS=$TEST_SUMMARY_ARTIFACTS"
export TESTSUITE=${11}; echo "TESTSUITE=>$TESTSUITE"
export TESTARGS=${12}; echo "TESTARGS=$TESTARGS"
export SHARETMPDIR="/homes/hadoopqa/hadoopqaTest-`date +%s`";mkdir $SHARETMPDIR;echo $SHARETMPDIR

## Extracted Variables
export TESTCASENAME=""; echo "TESTCASENAME=$TESTCASENAME"
export TESTCASE_DESC="Not Mentioned"; echo "TESTCASE_DESC=$TESTCASE_DESC"
export REASONS=""; echo "REASONS=$REASONS"
export COMMAND_EXIT_CODE=0; echo "COMMAND_EXIT_CODE=$COMMAND_EXIT_CODE"
export SCRIPT_EXIT_CODE=0; echo "SCRIPT_EXIT_CODE=$SCRIPT_EXIT_CODE"
export ASSERTCOUNT=0; echo "ASSERTCOUNT=$ASSERTCOUNT";
export TESTCASE_STARTTIME=0; echo "TESTCASE_STARTTIME=$TESTCASE_STARTTIME"
export TESTCASE_ID=10; echo "TESTCASE_ID=$TESTCASE_ID"
export JOBTRACKER="None"; echo "JOBTRACKER=$JOBTRACKER"

