#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TIMESTAMP=`date +%y%m%d-%T`
filename="/tmp/scan.log.$TIMESTAMP"

set -x
$script_dir/scan_clusters $* 2>&1 | tee $filename
set +x

echo
echo "==========================================="
echo "SUMMARY"
echo "==========================================="
$script_dir/parse_scan_clusters $filename
echo 

rm $filename

