#!/bin/bash

clusters=$*
TIMESTAMP=`date +%y%m%d-%T`
filename="/tmp/scan.log.$TIMESTAMP"
./scripts/scan_clusters $clusters 2>&1 | tee $filename

echo "==========================================="
echo "SUMMARY"
echo "==========================================="
./scripts/parse_scan_clusters $filename

rm $filename

