#!/bin/bash

TIMESTAMP=`date +%y%m%d-%T`

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
output_dir=$script_dir/../target
mkdir -p $output_dir
cluster_info_log="$output_dir/cluster_info.log"

set -x
$script_dir/scan_clusters $* 2>&1 | tee $cluster_info_log
set +x

echo
echo "==========================================="
echo "SUMMARY"
echo "==========================================="
$script_dir/parse_scan_clusters $cluster_info_log
echo 

# ## Sending mail to user 
# if [ "X${EMAIL_USER}X" != "XX" ];then
#     if [ "X${JOB_URL}X" == "XX" ];then
#         sub="HadoopQERegression-${HADOOPQE_TEST_BRANCH}"
#     else
#         sub=`echo $JOB_URL | sed -e 's/.*job\/\(.*\)\/$/\1/'`
#     fi
#     SUBJECT="TEST_REPORT: $sub   VERSION: $VERSION   STARTTIME: $STARTTIME"
#     EMAIL="$EMAIL_USER@yahoo-inc.com"
# 
#     set -x
#     /bin/mail -s "$SUBJECT" "$EMAIL" < $summaryfilename
#     set +x
#     if [ "$?" == "0" ];then
#         echo "Email is sent successfully to $EMAIL"
#     else
#         echo "Email could not be sent to $EMAIL"
#     fi
# fi


