#!/bin/bash

set -x
rm -f coretest_jar*.tgz
/usr/local/bin/yinst fetch -branch nightly coretest_jar
tar xzvf coretest_jar*.tgz etc/coretest/java/lib/coretest-1.0-SNAPSHOT.jar
cp ./etc/coretest/java/lib/coretest-1.0-SNAPSHOT.jar /tmp/