#!/bin/bash

echo WORKSPACE=$WORKSPACE

set -x

# yjava_byauth
/usr/local/bin/yinst fetch yjava_byauth -outputfile $WORKSPACE/yinst_fetch_dependencies/yjava_byauth_fetch/yjava_byauth.tgz
gunzip -f $WORKSPACE/yinst_fetch_dependencies/yjava_byauth_fetch/yjava_byauth.tgz
tar -xf $WORKSPACE/yinst_fetch_dependencies/yjava_byauth_fetch/yjava_byauth.tar -C $WORKSPACE/yinst_fetch_dependencies/yjava_byauth_fetch/

# yjava_jetty-9.0.6.v20130930_0.47
/usr/local/bin/yinst fetch yjava_jetty-9.0.6.v20130930_0.47 -br current -outputfile $WORKSPACE/yinst_fetch_dependencies/yjava_jetty_fetch/yjava_jetty.tgz
gunzip -f $WORKSPACE/yinst_fetch_dependencies/yjava_jetty_fetch/yjava_jetty.tgz
tar -xf $WORKSPACE/yinst_fetch_dependencies/yjava_jetty_fetch/yjava_jetty.tar -C $WORKSPACE/yinst_fetch_dependencies/yjava_jetty_fetch/

# yspark_yarn-0.9.0.1.1403181145_hadoop2
/usr/local/bin/yinst fetch yspark_yarn-0.9.0.1.1403181145_hadoop2 -br quarantine -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/

# ystorm_contrib
/usr/local/bin/yinst fetch ystorm_contrib -br quarantine -outputfile $WORKSPACE/yinst_fetch_dependencies/ystorm_contrib_fetch/ystorm_contrib.tgz
gunzip -f $WORKSPACE/yinst_fetch_dependencies/ystorm_contrib_fetch/ystorm_contrib.tgz
tar -xf $WORKSPACE/yinst_fetch_dependencies/ystorm_contrib_fetch/ystorm_contrib.tar -C $WORKSPACE/yinst_fetch_dependencies/ystorm_contrib_fetch/

# ystorm
/usr/local/bin/yinst fetch ystorm -br quarantine -outputfile $WORKSPACE/yinst_fetch_dependencies/ystorm_fetch/ystorm.tgz
gunzip -f $WORKSPACE/yinst_fetch_dependencies/ystorm_fetch/ystorm.tgz
tar -xf $WORKSPACE/yinst_fetch_dependencies/ystorm_fetch/ystorm.tar -C $WORKSPACE/yinst_fetch_dependencies/ystorm_fetch/
