#!/bin/bash

function usage {
    echo
    echo "USAGE"
    echo "-----------------------------------------------------------------------------------"
    echo "/bin/sh $0 <option1> <values1> <option2> <values2> ...
The options
        -c|--cluster <cluster name>          : cluster name
        [ -f|            <conf file>       ] : hadooptest configuration file
        [ -g|--gateway   <aateway>         ] : remote gateway host
        [ -i|--install                     ] : transport packages to remote host only
        [ -n|--nopasswd                    ] : no password prompt
        [ -s|--source    <source root dir> ] : source root directory
        [ -u|--user      <remote user>     ] : remote user; e.g. hadoopqa
        [ -w|--workspace <workspace>       ] : remote workspace. Default remote workspace is 
                                               "/tmp/hadooptest-<REMOTE USER>-<CLUSTER>"
        [ -h|--help                        ] : help

Example:
$ cp_mvn_deps_to_gateway --cluster omegab -u hadoopqa
$ cp_mvn_deps_to_gateway --cluster omegas -u hadoopqa
$ cp_mvn_deps_to_gateway --cluster same -u hadoopqa
"
    exit 1
}

for arg; do 
    [[ "${arg:0:1}" == "-" ]] && delim="" || delim="\""
    if [ "${arg:0:2}" == "--" ]; 
       then args="${args} -${arg:2:1}" 
       else args="${args} ${delim}${arg}${delim}"
    fi
done

# reset the incoming args
eval set -- $args

INSTALL_ONLY=0
while getopts "c:f:g:s:t:u:w:inh" opt; do
        case $opt in
                c) CLUSTER=$OPTARG;;
                f) CONF=$OPTARG;;
                g) REMOTE_HOST=$OPTARG;;
                i) INSTALL_ONLY=1;;
                n) PASSWORD_OPTION="-n";;
                s) LOCAL_WORKSPACE=$OPTARG;;
                t) TESTS=$OPTARG;;
                u) REMOTE_USER=$OPTARG;;
                w) REMOTE_WORKSPACE=$OPTARG;;
                h) usage;;
                *) usage;;
        esac
done

if [ -z $CLUSTER ]; then
   echo "ERROR: Required CLUSTER value not defined!!!";
   exit 1;
fi

if [ -z $REMOTE_HOST ]; then
	echo "gateway unspecified: fetch host role: $rolename";
	rolename="grid_re.clusters.$CLUSTER.gateway"
	DEFAULT_REMOTE_HOST=`rocl -r $rolename -m`
fi
REMOTE_HOST=${REMOTE_HOST:=$DEFAULT_REMOTE_HOST}
echo "remote gateway host=$DEFAULT_REMOTE_HOST";

USER=`whoami`
REMOTE_USER=${REMOTE_USER:=`whoami`}
REMOTE_WORKSPACE=${REMOTE_WORKSPACE:="/tmp/hadooptest-$REMOTE_USER-$CLUSTER-staging"}

if [ "$REMOTE_USER" == "hadoopqa" ]; then
# 	ssh -t $REMOTE_HOST "sudo rm -rf $REMOTE_WORKSPACE;";
	set -x
	ssh -t $REMOTE_HOST "if [ -d $REMOTE_WORKSPACE ]; then sudo /bin/rm -rf $REMOTE_WORKSPACE; fi";
	set +x
else
	set -x
	ssh -t $REMOTE_HOST "if [ -d $REMOTE_WORKSPACE ]; then /bin/rm -rf $REMOTE_WORKSPACE; fi";
	set +x
fi

set -x
ssh -t $REMOTE_HOST "/bin/mkdir -p $REMOTE_WORKSPACE";
set +x

LOCAL_WORKSPACE=${LOCAL_WORKSPACE:="/Users/$USER/git/hadooptest/hadooptest"}
LOCAL_WORKSPACE_TARGET_DIR="$LOCAL_WORKSPACE/target"

echo "CLUSTER='$CLUSTER'"
echo "LOCAL_WORKSPACE='$LOCAL_WORKSPACE'"
echo "REMOTE_HOST='$REMOTE_HOST'"
echo "REMOTE_WORKSPACE='$REMOTE_WORKSPACE'"
echo "TESTS='$TESTS'"
echo "INSTALL_ONLY='$INSTALL_ONLY'"

TGZ_DIR=/tmp
TGZ_FILE=hadoop_mvn_repo.tgz

set -x
MVN_DIR=${MVN_DIR:=".m2/repository/org/apache/hadoop"}
LOCAL_MVN_DIR="/Users/$USER/$MVN_DIR"
tar -zcf $TGZ_DIR/$TGZ_FILE -C $LOCAL_MVN_DIR .
scp $TGZ_DIR/$TGZ_FILE $REMOTE_HOST:$REMOTE_WORKSPACE

ssh -t $REMOTE_HOST "/bin/gtar fx $REMOTE_WORKSPACE/$TGZ_FILE -C $REMOTE_WORKSPACE";
if [ "$REMOTE_USER" == "hadoopqa" ]; then
    ssh -t $REMOTE_HOST "sudo chown -R hadoopqa $REMOTE_WORKSPACE;";
    REMOTE_MVN_DIR="~hadoopqa/$MVN_DIR"
else
    REMOTE_MVN_DIR="~/$MVN_DIR"
fi

ssh -t $REMOTE_HOST "sudo /bin/rm -rf $REMOTE_MVN_DIR/*";
ssh -t $REMOTE_HOST "sudo /bin/mv $REMOTE_WORKSPACE/* $REMOTE_MVN_DIR/";
set +x

