#!/bin/bash
set -x #echo on

# This script should be used to gather dependencies from a developer machine
# so that they can be checked into the framework repository.  The script
# takes all current jars from the local user's .m2 repository and puts them
# in a directory "dependencies" at the top level of the framework.  The script
# will wipe out the existing local m2 repository and run maven eclipse:eclipse
# targets, so use with care.

# Set the base directory as the dir that the script lives in.
BASEDIR="$( cd "$( dirname "$0" )" && pwd )"

# Remove all preexisting maven local dependencies
rm -rf ~/.m2/*

# Clean the existing dependencies directory
rm -rf $BASEDIR/../dependencies/*

# Build and install coretest, and gather its dependencies
cd $BASEDIR/../../../coretest/coretest
mvn eclipse:eclipse
mvn clean package -DskipTests
mvn install

# Get the dependencies for the project and build it
cd $BASEDIR/..
mvn eclipse:eclipse -Pprofile-eclipse
mvn clean package -DskipTests -Pprofile-eclipse

# Copy the local .m2 repo into the dependencies dir.
mkdir $BASEDIR/../dependencies
cp -R ~/.m2 $BASEDIR/../dependencies/

# Print out the size on disk for the .m2 and dependencies dirs.  They should
# match.
du -sk ~/.m2
du -sk $BASEDIR/../dependencies

# Add the dependencies to the git commit.  --all option adds new files,
# removes files in the repo no longer there on disk, and stages modified
# files that already exist in the repo.
git add --force --all $BASEDIR/../dependencies/*

