#!/usr/bin/env perl

use strict;
use warnings;
use FindBin qw($Bin $Script);
use Test::More;
use File::Copy;
use File::Find::Rule;
use File::Basename;

my $line;
my $fs_used_percentage;
my $fs_used_threshold=90;
my $df_header;
my $show_df_header=1;
my $show_cluster_header=1;
my $cluster;
my $prev_hostname="";
my $hostname;
my $version;
my $time;
my $tmpfile="/tmp/clusterinfo.raw";

my $output_dir="$Bin/../target";
mkdir $output_dir unless (-d $output_dir);
my $issues_log="$output_dir/cluster_issues.log";

system("rm -f $tmpfile");

open(my $fh2, '>', $issues_log) or die "Could not open file '$issues_log' $!";

sub print_cluster_header() {
    print("--------------------\n");
    print("cluster=$cluster\n");
    print("--------------------\n");

    print $fh2 "--------------------\n";
    print $fh2 "cluster=$cluster\n";
    print $fh2 "--------------------\n";

    $show_cluster_header=0;
}

sub print_df_header() {
    print($df_header);
    print $fh2 $df_header;
    $show_df_header=0;
}

# open call is not needed when opening the file specified as the first argument
# open(FILE1, $ARGV[0]);
while (<>) {
    # $. keep track of the current line number
    # printf("line %2d: %s", $., $_);

    $line = $_;

    if (($line =~ /^\Q+\E/) || 
        ($line =~ "Warning: Permanently added") ||
        ($line =~ "---------")) {
        next;
    }

    # Save the cluster header
    if ($line =~ m/(^cluster)\s+(.*)/) {
        $cluster = $2;
	system("echo -n \"$cluster, \" >> $tmpfile");
        $show_cluster_header=1;
        $show_df_header=1;
        next;
    }

    # Save the df header
    if ($line =~ /(.*)\s+(Filesystem)\s+(.*)/) {
        $df_header = $line;
        next;
    }

    $version="UNKNOWN";
    $time="UNKNOWN";

    if ($line =~ m/(^Hadoop.*:)\s+(.*)/) {
        $version = $2;
	system("echo -n \"$version, \" >> $tmpfile");
        next;
    }

    if ($line =~ m/(^Time.*:)\s+(.*)/) {
        $time = $2;
	system("echo -n \"$time, \" >> $tmpfile");
	system("echo `date -d $time +%s` >> $tmpfile");
        next;
    }

    # Check percentage
    if ($line =~ m/(.*)\s+(\d+)(%)\s+(.*)/) {
        $$fs_used_percentage=$2;
        if ($$fs_used_percentage > $fs_used_threshold) {
            print_cluster_header() if ($show_cluster_header == 1);
            print_df_header() if ($show_df_header == 1);
            print($line);
            print $fh2 $line;
        }
    } else {
        if ($line =~ "/vol/") {
            next;
        }
        print_cluster_header() if ($show_cluster_header == 1);
        printf("%s", $line);
        print $fh2 $line;

        # Attempt to reboot the node
        if (($_ =~ m/(.*)\s+(gsbl.*)(:.*)/) || 
            ($_ =~ m/(.*)\s+(gsta.*)(:.*)/) ||
            ($_ =~ m/(.*)\s+(.*.ygrid.yahoo.com)\s+(.*)/) ) {
            $hostname = $2;
            unless ($hostname =~ $prev_hostname) {
                # reboot the node
                print("ssh adm102.blue.ygrid.yahoo.com sudo -u hadoopqa /home/y/bin/flubber_conutil -m reboot $hostname\n");
                print $fh2 "ssh adm102.blue.ygrid.yahoo.com sudo -u hadoopqa /home/y/bin/flubber_conutil -m reboot $hostname\n";

                # system("ssh adm102.blue.ygrid.yahoo.com sudo -u hadoopqa /home/y/bin/flubber_conutil -m reboot $hostname");
                # Sorry, user hadoopqa is not allowed to execute '/home/y/bin/flubber_conutil -m reboot dense28.blue.ygrid.yahoo.com' as hadoopqa on adm102.blue.ygrid.yahoo.com.

                # bash-4.1$ ssh adm102.blue.ygrid.yahoo.com SUDO_USER=hadoopqa /home/y/bin/flubber_conutil -m reboot dense28.blue.ygrid.yahoo.com
                # User : hadoopqa does not have the required permissions. at /home/y/bin/flubber_conutil line 39.
            }
            $prev_hostname = $hostname;
        }       
    }
}

close $fh2;

my $cluster_usage_report="$output_dir/cluster_usage.log";
open(my $fh, '>', $cluster_usage_report) or die "Could not open file '$cluster_usage_report' $!";

print $fh "-------------------------------------------\n";
print $fh "cluster, version, time of last job\n";
print $fh "-------------------------------------------\n";
close $fh;
system("sort -k4 $tmpfile|cut -d, -f1-3 >> $cluster_usage_report");
system("cat $cluster_usage_report");

