#!/bin/bash

# Usage: 
# run_hadooptest -c <cluster name> [ -l <hadooptest lib directory> ]
# run_hadooptest -c faramir
# run_hadooptest -c faramir -t <test list>
# run_hadooptest -c faramir -l <libpath1>:<libpath2>:...
# run_hadooptest -c theoden -l /homes/philips -t hadooptest.regression.Version -n

function usage {
    echo 
    echo "USAGE"
    echo "-----------------------------------------------------------------------------------"
    echo "/bin/sh $0 <option1> <values1> <option2> <values2> ...
The options
        -c <cluster name> : cluster name
        [ -l <lib directory> ] : hadooptest lib directory 
        [ -t <test list> ] : test list 
        [ -n ] : no password prompt
"
    exit 1
}

PASSWORD_OPTION=${PASSWORD_OPTION:-"-password"}
HADOOPTEST_LIB=${HADOOPTEST_LIB:="/home/y/etc/hadooptest/java/lib"}

DEFAULT_TESTS="\
hadooptest.regression.CheckVersion \
hadooptest.regression.ChangeConf \
hadooptest.regression.RestartCluster \
hadooptest.regression.yarn.SleepJobRunner\
"
TESTS=${TESTS:="$DEFAULT_TESTS"}

while getopts "c:l:t:nh" opt; do
	case $opt in
		c) CLUSTER=$OPTARG;;
		l) HADOOPTEST_LIB=$OPTARG;;		
		n) PASSWORD_OPTION="no-password";;
		t) TESTS=$OPTARG;;
		h) usage;;
		*) usage;;
	esac
done

if [ -z $CLUSTER ]; then
   echo "ERROR: Required CLUSTER value not defined!!!";
   exit 1;
fi


# Setup Hadoop Env Variables (e.g. HADOOP_COMMON_HOME, HADOOP_CONF_DIR, etc

CLASSPATH="\
/home/y/lib/jars/junit.jar:\
/home/gs/gridre/yroot.$CLUSTER/conf/hadoop/:\
$HADOOPTEST_LIB/hadooptest-1.0-SNAPSHOT.jar:\
$HADOOPTEST_LIB/hadooptest-1.0-SNAPSHOT-tests.jar"

HADOOP_JAR_PATHS="
/home/gs/gridre/yroot.$CLUSTER/share/hadoop/share/hadoop/common/lib \
/home/gs/gridre/yroot.$CLUSTER/share/hadoop-*/share/hadoop/common \
/home/gs/gridre/yroot.$CLUSTER/share/hadoop-*/share/hadoop/common/lib \
/home/gs/gridre/yroot.$CLUSTER/share/hadoop-*/share/hadoop/yarn \
/home/gs/gridre/yroot.$CLUSTER/share/hadoop-*/share/hadoop/yarn/lib \
/home/gs/gridre/yroot.$CLUSTER/share/hadoop-*/share/hadoop/mapreduce \ 
/home/gs/gridre/yroot.$CLUSTER/share/hadoop-*/share/hadoop/hdfs
"

for i in $HADOOP_JAR_PATHS
do
  CLASSPATH=${CLASSPATH}:`echo -en ${i}`/*
done

echo "CLASSPATH=$CLASSPATH"

# TODO: long term this should move into the java test framework
if [ "$PASSWORD_OPTION" != 'no-password' ]; then 
   USER=`whoami`
   if [ $USER == 'hadoopqa' ];then
      echo "Headless user 'hadoopqa' requires no password."
   else 
      stty -echo
      /usr/kerberos/bin/kinit $USER@DS.CORP.YAHOO.COM
      stty echo
   fi
fi

set -x
/home/y/bin/java -cp $CLASSPATH org.junit.runner.JUnitCore $TESTS
set +x


