#!/bin/bash

# $ validate_proxy <source cluster> <target cluster> <hdfs test dir> <local proxy> [remote proxy]
# $ validate_proxy densed densec /HTF/testdata/dfs/ gsbl90225.blue.ygrid.yahoo.com
# $ validate_proxy densed hbasetan1 /HTF/testdata/dfs/ fsbl824n00.blue.ygrid.yahoo.com fsta773n00.tan.ygrid.yahoo.com

SOURCE_CLUSTER=$1
TARGET_CLUSTER=$2
HDFS_TEST_DIR=$3
LOCAL_PROXY=$4
REMOTE_PROXY=$5

ADM_HOST=${ADM_HOST:="devadm102.blue.ygrid.yahoo.com"}
HDFS_TEST_DIR=${HDFS_TEST_DIR:="/HTF/testdata/dfs/"}
PROXY_PORT=4443

if [ "$#" -lt 4 ]; then
    echo "USAGE: At least 3 parameters are required:"
    echo "$ validate_proxy <source cluster> <target cluster> <hdfs test dir> <local proxy> [remote proxy]"
    exit 1;
fi

# Determine the source and target NN.
# First determine if HA / NN Alias is being used:
function fetch_NN() {
  CLUSTER=$1
  NN=`yinst range -ir "(@grid_re.clusters.$CLUSTER.namenode_alias)" 2>/dev/null`
  RC=$?
  if [[ "$RC" == "0" ]]; then
    curl -m 3 -s "http://$NN:50070/jmx?get=Hadoop:service=NameNode,name=NameNodeStatus::State" 2>&1 > /dev/null
    RC=$?
  fi
  if [[ "$RC" != 0 ]]; then
      NN=`yinst range -igor_range "@grid_re.clusters.$CLUSTER.namenode"`
  fi
  echo $NN
}

SOURCE_NN=`fetch_NN $SOURCE_CLUSTER`
TARGET_NN=`fetch_NN $TARGET_CLUSTER`
echo "SOURCE_NN=$SOURCE_NN"
echo "TARGET_NN=$TARGET_NN"

LOG_DIR="/home/y/logs/trafficserver"
LOG="$LOG_DIR/extended2.log"

EC=0

src_hadoop_version=`ssh ${SOURCE_NN} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /home/gs/gridre/yroot.${SOURCE_CLUSTER}/share/hadoop/bin/hadoop version|head -1|cut -d' ' -f2`
tgt_hadoop_version=`ssh ${TARGET_NN} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /home/gs/gridre/yroot.${TARGET_CLUSTER}/share/hadoop/bin/hadoop version|head -1|cut -d' ' -f2`
local_proxy_version=`ssh $LOCAL_PROXY yinst ls ats`;
build_desc="Build Description: "
build_desc+="src=${SOURCE_CLUSTER} ${src_hadoop_version};"
build_desc+="tgt=${TARGET_CLUSTER} ${tgt_hadoop_version};"
build_desc+="localproxy=$local_proxy_version;"
if [ -n $REMOTE_PROXY ]; then
    remote_proxy_version=`ssh $REMOTE_PROXY yinst ls ats`;
    build_desc+="remoteproxy=$remote_proxy_version"
fi
echo "$build_desc"

if [ "$#" -eq 4 ]; then
  PROXY=$LOCAL_PROXY
  echo -n "----> Validate intra-colo cross-cluster distcp to/from clusters '$SOURCE_CLUSTER'/'$TARGET_CLUSTER'"
  echo " pass through the proxy host '$PROXY':"
  for NN in $SOURCE_NN $TARGET_NN; do
    echo "--> Check for references to cluster NN '$NN' in proxy log:"
    set -x
    # files last modified in the last 3 hours (n*24 hours ago).
    ssh $PROXY "find $LOG_DIR -mtime -0.125 -name extended2*"
    ssh $PROXY "find $LOG_DIR -mtime -0.125 -name extended2* | xargs grep -q \"GET http://$NN:50070/webhdfs/v1"$HDFS_TEST_DIR"file_\""
    RC=$?
    EC=$((EC+$RC))
    set +x
  done
else
  echo -n "----> Validate cross-colo distcp to/from clusters '$SOURCE_CLUSTER'/'$TARGET_CLUSTER'"
  echo " pass through the proxy hosts '$LOCAL_PROXY'/'$REMOTE_PROXY':"
  echo "--> Check for references to the REMOTE PROXY $REMOTE_PROXY in the LOCAL PROXY log:"
  set -x
  ssh $LOCAL_PROXY "find $LOG_DIR -mtime -0.125 -name extended2*"
  ssh $LOCAL_PROXY "find $LOG_DIR -mtime -0.125 -name extended2* | xargs grep -q \"GET https://$REMOTE_PROXY:$PROXY_PORT/webhdfs/v1"$HDFS_TEST_DIR"file_\""
  RC=$?
  EC=$((EC+$RC))
  set +x

  echo "--> Check for references to the TARGET CLUSTER NN '$TARGET_NN' in the REMOTE PROXY log:"
  set -x
  # Need to hop over the adm host due to cross colo ACL restriction.
  ssh $ADM_HOST ssh $REMOTE_PROXY "find $LOG_DIR -mtime -0.125 -name extended2*"
  ssh $ADM_HOST "ssh $REMOTE_PROXY \"find $LOG_DIR -mtime -0.125 -name extended2* | xargs grep -q 'GET http://$TARGET_NN:50070/webhdfs/v1${HDFS_TEST_DIR}file_'\""
  RC=$?
  EC=$((EC+$RC))
  set +x
fi

echo "EC=$EC"
exit $EC
