#!/bin/bash

# $ validate_proxy <source cluster> <target cluster> <local proxy> [remote proxy]
# $ validate_proxy densed densec gsbl90225.blue.ygrid.yahoo.com 
# $ validate_proxy densed hbasetan1 fsbl824n00.blue.ygrid.yahoo.com fsta773n00.tan.ygrid.yahoo.com

SOURCE_CLUSTER=$1
TARGET_CLUSTER=$2
LOCAL_PROXY=$3
REMOTE_PROXY=$4

if [ "$#" -lt 3 ]; then
    echo "USAGE: At least 3 parameters are required:"
    echo "$ validate_proxy <source cluster> <target cluster> <local proxy> [remote proxy]"
    exit 1;
fi

# Determine the source and target NN.
# First determine if HA / NN Alias is being used:
function set_NN() {
  CLUSTER=$1
  NN=`yinst range -ir "(@grid_re.clusters.$CLUSTER.namenode_alias)"`
  set -x
  curl -m 3 -s "http://$NN:50070/jmx?get=Hadoop:service=NameNode,name=NameNodeStatus::State" 2>&1 > /dev/null
  RC=$?
  set +x
  if [[ "$RC" != 0 ]]; then
      NN=`yinst range -igor_range "@grid_re.clusters.$CLUSTER.namenode"`
  fi
  echo $NN
}

SOURCE_NN=`set_NN $SOURCE_CLUSTER`
TARGET_NN=`set_NN $TARGET_CLUSTER`
echo "SOURCE_NN=$SOURCE_NN"
echo "TARGET_NN=$TARGET_NN"

LOG_DIR="/home/y/logs/trafficserver"
LOG="$LOG_DIR/extended2.log"

EC=0
if [ "$#" -eq 3 ]; then
  PROXY=$LOCAL_PROXY
  echo "----> Validate intra-colo cross-cluster distcp to/from clusters '$SOURCE_CLUSTER'/'$TARGET_CLUSTER'"
  echo "      went through the proxy host '$PROXY':"
  for NN in $SOURCE_NN $TARGET_NN; do
    echo "--> Check for references to cluster NN '$NN' in proxy log:"
    set -x
    ssh $PROXY "find $LOG_DIR -mtime -0.125 | xargs grep -q \"GET http://$NN:50070/webhdfs/v1/HTF/testdata/dfs/file_\""
    RC=$?
    EC=$((EC+$RC))
    set +x
  done
else
  echo "----> Validate cross-colo distcp to/from clusters '$SOURCE_CLUSTER'/'$TARGET_CLUSTER'"
  echo "      went through the proxy hosts '$LOCAL_PROXY'/'$REMOTE_PROXY':"
  echo "--> Check for references to the REMOTE PROXY $REMOTE_PROXY in the LOCAL PROXY log:"
  set -x
  ssh $LOCAL_PROXY "find $LOG_DIR -mtime -0.125 | xargs grep -q \"GET https://$REMOTE_PROXY:4443/webhdfs/v1/HTF/testdata/dfs/file_\""
  RC=$?
  EC=$((EC+$RC))
  set +x

  echo "--> Check for references to the TARGET CLUSTER NN '$TARGET_NN' in the REMOTE PROXY log:"
  set -x
  ssh $REMOTE_PROXY "find $LOG_DIR -mtime -0.125 | xargs grep -q \"GET http://$TARGET_NN:50070/webhdfs/v1/HTF/testdata/dfs/file_\""
  RC=$?
  EC=$((EC+$RC))
  set +x
fi

echo "EC=$EC"
exit $EC
