#!/bin/bash

# yinst install all of the perl packages from dist, that are required for
# perl support to be able to run the run_hadooptest and run_hadooptest_remote
# scripts. This is most useful on a system or yroot that didn't previously
# have any yahoo perl support installed on it. Many existing systems will
# already have many of these packages installed.
yinst i perl -same -live
yinst i perlbase -same -live
yinst i local_perl_compat -same -live
yinst i perl_Yahoo_Backyard_SingleSignOn
yinst i perl-File-Find-Rule