#!/bin/bash                                                                                                                                                                                                                                                                                                                   

#################################################################################
# Run disk_usage script on all cluster nodes
# This script should be run as hadoopqa
# ./cluster_du openqe73blue -q
# ./cluster_du openqe73blue -q -c
# ./cluster_du openqe73blue -q -c -v
#################################################################################

CLUSTER=$1
if [[ -z $CLUSTER ]]; then
    echo "ERROR: required CLUSTER arg is not passed in!!!"
    exit 1
fi

# Process all arguments except the first one
DISK_USAGE_ARG="${@:2}"

SSH_OPT="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
SSH="ssh $SSH_OPT"
SCP="scp $SSH_OPT"
ADM_HOST=${ADM_HOST:="devadm102.blue.ygrid.yahoo.com"}

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source_file="$SCRIPT_DIR/disk_usage"
target_file="/tmp/disk_usage"

echo "--> Copy script disk_usage to admin host $ADM_HOST"
set -x
$SCP $source_file $ADM_HOST:$target_file
RC=$?
set +x
if [[ $RC != 0 ]]; then
    echo "scp to adm host $ADM_HOST failed. Exit!!!"
    exit 1;
fi

echo "--> Copy script disk_usage from admin host $ADM_HOST to cluster $CLUSTER"
set -x
NODES_CSV=`$SSH $ADM_HOST yinst range -ir @grid_re.clusters.$CLUSTER,@grid_re.clusters.$CLUSTER.gateway|tr '\n' ','|sed 's/.$//'`
set +x

set -x
$SSH $ADM_HOST "PDSH_SSH_ARGS_APPEND='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' \
sudo /home/y/bin64/pdcp -w $NODES_CSV $target_file $target_file"
RC=$?
set +x
if [[ $RC != 0 ]]; then
    echo "scp to cluster $CLUSTER failed."
fi

echo "--> Validate: script disk_usage copied successfully to cluster $CLUSTER"
set -x
$SSH $ADM_HOST "sudo pdsh -r @grid_re.clusters.$CLUSTER,@grid_re.clusters.$CLUSTER.gateway 'ls -l $target_file'"
set +x

echo "--> Check disk usage"
set -x
$SSH $ADM_HOST "sudo pdsh -r @grid_re.clusters.$CLUSTER,@grid_re.clusters.$CLUSTER.gateway '/tmp/disk_usage $DISK_USAGE_ARG'"
set +x

echo "--> Get report from cluster $CLUSTER"
set -x
$SSH $ADM_HOST "sudo pdsh -r @grid_re.clusters.$CLUSTER,@grid_re.clusters.$CLUSTER.gateway 'cat /tmp/du.out'" > $SCRIPT_DIR/du.txt
cat $SCRIPT_DIR/du.txt
set +x

