#!/bin/bash

#################################################################################
# Update the clusters yaml file in the hadoop_releases git repo
# Required Parameters:
# 1) component - (e.g. hadoop_core)
# 2) serial - the serial id
# 3) clusters  - comma separated list with one or more clusters
# (e.g. 'axonitered', 'axonitered, kryptonitered')
#
# USAGE:
# $ ./update_clusters_yaml hadoop_core axonitered 20150803184432
#################################################################################

echo "Update the clusters yaml file in the hadoop_releases git repo:"

# Get the full path script directory
SCRIPT_DIR=`dirname $(readlink -f $0)`
TS=`date +%s`
GIT_REPO="git@git.corp.yahoo.com:GridSE/hadoop_releases.git"
GIT_DIR="$SCRIPT_DIR/hadoop_releases.$TS"

component=$1
# E.g. `date -u +\%Y\%m\%d\%H\%M\%S`
serial=$2
clusters=$3

if [[ -z $component ]]; then
  echo "ERROR: Required component parameter is empty!!!"
  exit 1
fi

if [[ -z $serial ]]; then
  echo "ERROR: Required serial parameter is empty!!!"
  exit 1
fi

if [[ -z $clusters ]]; then
  echo "ERROR: Required cluster parameter is empty!!!"
  exit 1
fi

echo "component='$component'"
echo "serial='$serial'"
echo "clusters='$clusters'"

#################################################################################
# Clone git repo
#################################################################################
echo "---> Clone git repo '$GIT_REPO':"
set -x
git clone $GIT_REPO $GIT_DIR
ls -ld $GIT_DIR
cd $GIT_DIR
pwd
set +x

#################################################################################
# Update the clusters yaml file
#################################################################################
set -x
$GIT_DIR/scripts/update_clusters.pl -cluster $clusters -filename clusters.yaml -bundle $component -serial $serial -w
set +x

