#!/bin/bash

if [ $# -ne 1 ];then
  echo "Error: need the CLUSTER name to compile against"
  exit 1
fi
CLUSTER=$1
echo "Info: building against $CLUSTER"


if [ ! -d outTokenRenewalTest_doasBlock_cleanUgi_oldApi_webhdfs ]
then
  mkdir outTokenRenewalTest_doasBlock_cleanUgi_oldApi_webhdfs
fi 

javac -Xlint:deprecation -Xlint:unchecked  -cp  `/home/gs/gridre/yroot.$CLUSTER/share/hadoop/bin/hadoop  --config /home/gs/gridre/yroot.$CLUSTER/conf/hadoop  classpath` -d outTokenRenewalTest_doasBlock_cleanUgi_oldApi_webhdfs TokenRenewalTest_doasBlock_cleanUgi_oldApi_webhdfs.java
if [ $? -ne 0 ]
then
   echo "Error compiling"
   exit 1
fi

jar -cvf TokenRenewalTest_doasBlock_cleanUgi_oldApi_webhdfs.jar -C outTokenRenewalTest_doasBlock_cleanUgi_oldApi_webhdfs .
if [ $? -ne 0 ]
then
   echo "Error packaging jar"
   exit 1
fi

echo "RUNME: /home/gs/gridre/yroot.$CLUSTER/share/hadoop/bin/hadoop --config /home/gs/gridre/yroot.$CLUSTER/conf/hadoop/ jar `pwd`/TokenRenewalTest_doasBlock_cleanUgi_oldApi_webhdfs.jar TokenRenewalTest_doasBlock_cleanUgi_oldApi_webhdfs" 

